<?php

namespace Container4qlD7J5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRechercheControllerrechercheInscriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VtrKQed.App\Controller\RechercheController::rechercheInscription()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VtrKQed.App\\Controller\\RechercheController::rechercheInscription()'] = ($container->privates['.service_locator.VtrKQed'] ?? $container->load('get_ServiceLocator_VtrKQedService'))->withContext('App\\Controller\\RechercheController::rechercheInscription()', $container);
    }
}
