<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ66d2mI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ66d2mI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ66d2mI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ66d2mI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ66d2mI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q66d2mI',
    'container.build_id' => '7c6a62c8',
    'container.build_time' => 1744306664,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ66d2mI');
