<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPfxmvrJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPfxmvrJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPfxmvrJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPfxmvrJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPfxmvrJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PfxmvrJ',
    'container.build_id' => '1b0ff296',
    'container.build_time' => 1742910420,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPfxmvrJ');
